name: Automated robot to update uberAgent ESA sigma rules automatically

on: [push]
  
jobs:
  build:

    runs-on: ubuntu-latest

    env:
      PYTHONUNBUFFERED: 1

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install markdown
        pip install markdown-link-attr-modifier
    - name: build
      run: |
        git clone https://github.com/vastlimits/sigma.git
        cd sigma
        git checkout feature/ame-7.0
        cd tools
        pip install PyYAML
        pip install pymisp
        pip install progressbar2
        pip install ruamel.yaml
        pip install termcolor
        pip install sigma
        python sigmac -I --target uberagent -r ../rules/
        cp -v uberAgent-ESA-am-sigma-critical.conf ../../rules/
        cp -v uberAgent-ESA-am-sigma-high.conf ../../rules/
        cp -v uberAgent-ESA-am-sigma-low.conf ../../rules/
        cp -v uberAgent-ESA-am-sigma-medium.conf ../../rules/
    - name: push
      uses: actions-x/commit@v6
      with:
        files: rules/uberAgent-ESA-am-sigma-low.conf, rules/uberAgent-ESA-am-sigma-medium.conf, rules/uberAgent-ESA-am-sigma-high.conf, rules/uberAgent-ESA-am-sigma-critical.conf
        
